# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: no-commit-to-branch
      - id: check-case-conflict
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-toml
      - id: requirements-txt-fixer
        args:
          [
            "--branch",
            "main",
            "--pattern",
            "^(feature|bugfix|improvement|library|prerelease|release|hotfix)\_[a-z0-9._-]+$",
          ]

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: ["--line-length=500"]


  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   # # type: ignore can be used to suspress mypy checks
  #   hooks:
  #     - id: mypy
        # args: [--show-error-codes, --ignore-missing-imports]
        
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    # noqa or # noqa: E234 can be used to suspress flake8 checks
    hooks:
      - id: flake8
        args: [
          "--max-line-length=500",
          "--ignore=E305",
          "--max-complexity=10",
          "--filename=*.py",
        ]

  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3'  # or any later Vulture version
    hooks:
      - id: vulture
        args: [
          ".",
          "--min-confidence=61"
        ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit