FROM apache/airflow:2.9.2
COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt

USER root

RUN apt update -y && apt install git -y

# COPY quarto.sh /
# RUN cd / && bash /quarto.sh